import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Azure Databricks: Multi-Agent RAG Operations Portal\n",
    "\n",
    "This notebook implements a complete **Multi-Agent RAG** system querying a Delta Table in Azure Databricks. It runs natively using PySpark SQL and supports both a **Local NLP Rule Engine** and a live **Gemini API** tool-use orchestrator."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# COMMAND ----------\n",
    "# MAGIC %pip install faker google-genai"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Step 1: Generate 500 Initial Orders and Save as Delta Table\n",
    "We will write the seed dataset directly to the catalog table `adb_core_data_dev_aue.default.orders` using PySpark."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# COMMAND ----------\n",
    "import json\n",
    "import random\n",
    "import pandas as pd\n",
    "from datetime import datetime, timedelta\n",
    "from faker import Faker\n",
    "from pyspark.sql import SparkSession\n",
    "\n",
    "fake = Faker()\n",
    "spark = SparkSession.builder.getOrCreate()\n",
    "\n",
    "CATEGORIES = {\n",
    "    \"Electronics\": [\n",
    "        {\"name\": \"Wireless Headphones\", \"price\": 89.99},\n",
    "        {\"name\": \"Mechanical Keyboard\", \"price\": 129.99},\n",
    "        {\"name\": \"Smart Watch\", \"price\": 199.99},\n",
    "        {\"name\": \"Bluetooth Speaker\", \"price\": 49.99},\n",
    "    ],\n",
    "    \"Apparel\": [\n",
    "        {\"name\": \"Organic Cotton Hoodie\", \"price\": 65.00},\n",
    "        {\"name\": \"Running Shoes\", \"price\": 110.00},\n",
    "        {\"name\": \"Denim Jacket\", \"price\": 85.00},\n",
    "    ],\n",
    "    \"Home & Kitchen\": [\n",
    "        {\"name\": \"Digital Air Fryer\", \"price\": 99.99},\n",
    "        {\"name\": \"Stainless Steel Water Bottle\", \"price\": 24.99},\n",
    "        {\"name\": \"Smart Coffee Maker\", \"price\": 149.99},\n",
    "    ],\n",
    "    \"Books\": [\n",
    "        {\"name\": \"Data Engineering Handbook\", \"price\": 45.99},\n",
    "        {\"name\": \"Sci-Fi Novel: Horizon's Edge\", \"price\": 14.99},\n",
    "    ],\n",
    "    \"Fitness\": [\n",
    "        {\"name\": \"Non-Slip Yoga Mat\", \"price\": 29.99},\n",
    "        {\"name\": \"Adjustable Dumbbells Set\", \"price\": 249.99},\n",
    "    ]\n",
    "}\n",
    "\n",
    "STATUSES = [\"Pending\", \"Processing\", \"Shipped\", \"Delivered\", \"Cancelled\", \"Refunded\"]\n",
    "CARRIERS = [\"FedEx\", \"UPS\", \"DHL\", \"USPS\"]\n",
    "\n",
    "orders_data = []\n",
    "base_date = datetime.now() - timedelta(days=45)\n",
    "\n",
    "for i in range(1, 501):\n",
    "    order_id = f\"ORD-{1000 + i}\"\n",
    "    customer_name = fake.name()\n",
    "    email = f\"{customer_name.lower().replace(' ', '.')}@{fake.free_email_domain()}\"\n",
    "    phone = fake.phone_number()\n",
    "    \n",
    "    days_offset = random.random() * 45\n",
    "    order_time = base_date + timedelta(days=days_offset)\n",
    "    order_date_str = order_time.strftime(\"%Y-%m-%d %H:%M:%S\")\n",
    "    \n",
    "    status = random.choices(STATUSES, weights=[8, 15, 20, 47, 6, 4], k=1)[0]\n",
    "    \n",
    "    num_items = random.randint(1, 3)\n",
    "    items_list = []\n",
    "    total_amount = 0.0\n",
    "    for _ in range(num_items):\n",
    "        cat = random.choice(list(CATEGORIES.keys()))\n",
    "        prod = random.choice(CATEGORIES[cat])\n",
    "        \n",
    "        existing = next((x for x in items_list if x[\"name\"] == prod[\"name\"]), None)\n",
    "        qty = random.randint(1, 2)\n",
    "        if existing:\n",
    "            existing[\"quantity\"] += qty\n",
    "        else:\n",
    "            items_list.append({\n",
    "                \"category\": cat,\n",
    "                \"name\": prod[\"name\"],\n",
    "                \"price\": prod[\"price\"],\n",
    "                \"quantity\": qty\n",
    "            })\n",
    "        total_amount += prod[\"price\"] * qty\n",
    "\n",
    "    total_amount = round(total_amount, 2)\n",
    "    shipping_address = fake.street_address()\n",
    "    city = fake.city()\n",
    "    zip_code = fake.zipcode()\n",
    "    country = \"United States\"\n",
    "    \n",
    "    carrier = \"\"\n",
    "    tracking_number = \"\"\n",
    "    estimated_delivery = \"\"\n",
    "    \n",
    "    if status in [\"Shipped\", \"Delivered\", \"Refunded\"]:\n",
    "        carrier = random.choice(CARRIERS)\n",
    "        tracking_number = f\"1Z{random.randint(100000000000, 999999999999)}\"\n",
    "        ship_days = random.randint(1, 3)\n",
    "        ship_time = order_time + timedelta(days=ship_days)\n",
    "        est_del_time = ship_time + timedelta(days=random.randint(2, 5))\n",
    "        estimated_delivery = est_del_time.strftime(\"%Y-%m-%d\")\n",
    "    elif status == \"Processing\":\n",
    "        est_del_time = order_time + timedelta(days=random.randint(4, 7))\n",
    "        estimated_delivery = est_del_time.strftime(\"%Y-%m-%d\")\n",
    "    elif status == \"Pending\":\n",
    "        est_del_time = order_time + timedelta(days=random.randint(5, 8))\n",
    "        estimated_delivery = est_del_time.strftime(\"%Y-%m-%d\")\n",
    "\n",
    "    notes = [f\"[{order_time.strftime('%Y-%m-%d %H:%M:%S')}] Order created. Total: ${total_amount}\"]\n",
    "    if status != \"Pending\" and status != \"Cancelled\":\n",
    "        processing_time = order_time + timedelta(hours=random.randint(2, 24))\n",
    "        notes.append(f\"[{processing_time.strftime('%Y-%m-%d %H:%M:%S')}] Payment verified. Order moved to Processing.\")\n",
    "        if status in [\"Shipped\", \"Delivered\", \"Refunded\"]:\n",
    "            ship_time = processing_time + timedelta(days=random.randint(1, 2))\n",
    "            notes.append(f\"[{ship_time.strftime('%Y-%m-%d %H:%M:%S')}] Dispatched via {carrier}. Tracking: {tracking_number}\")\n",
    "            if status in [\"Delivered\", \"Refunded\"]:\n",
    "                delivery_time = ship_time + timedelta(days=random.randint(2, 4))\n",
    "                notes.append(f\"[{delivery_time.strftime('%Y-%m-%d %H:%M:%S')}] Delivered to front door.\")\n",
    "                if status == \"Refunded\":\n",
    "                    refund_time = delivery_time + timedelta(days=random.randint(1, 5))\n",
    "                    notes.append(f\"[{refund_time.strftime('%Y-%m-%d %H:%M:%S')}] Refund processed.\")\n",
    "    elif status == \"Cancelled\":\n",
    "        cancel_time = order_time + timedelta(hours=random.randint(1, 12))\n",
    "        notes.append(f\"[{cancel_time.strftime('%Y-%m-%d %H:%M:%S')}] Order cancelled.\")\n",
    "\n",
    "    support_notes_str = \"\\n\".join(notes)\n",
    "    \n",
    "    orders_data.append({\n",
    "        \"order_id\": order_id,\n",
    "        \"customer_name\": customer_name,\n",
    "        \"email\": email,\n",
    "        \"phone\": phone,\n",
    "        \"order_date\": order_date_str,\n",
    "        \"status\": status,\n",
    "        \"total_amount\": total_amount,\n",
    "        \"shipping_address\": shipping_address,\n",
    "        \"city\": city,\n",
    "        \"zip_code\": zip_code,\n",
    "        \"country\": country,\n",
    "        \"carrier\": carrier,\n",
    "        \"tracking_number\": tracking_number,\n",
    "        \"estimated_delivery\": estimated_delivery,\n",
    "        \"items\": json.dumps(items_list),\n",
    "        \"support_notes\": support_notes_str\n",
    "    })\n",
    "\n",
    "# Save as Spark DataFrame in catalog 'adb_core_data_dev_aue.default.orders'\n",
    "pdf = pd.DataFrame(orders_data)\n",
    "df = spark.createDataFrame(pdf)\n",
    "df.write.format(\"delta\").mode(\"overwrite\").saveAsTable(\"adb_core_data_dev_aue.default.orders\")\n",
    "print(\"Delta Table 'adb_core_data_dev_aue.default.orders' generated and loaded with 500 seeds!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Step 2: Spark Structured Streaming Ingest (5000 + 5000 orders)\n",
    "Here, we set up a real-time ingestion pipeline. We will define a stream reader to ingest new CSV files as they land in `/tmp/orders_raw/` and append them directly to our catalog Delta table `adb_core_data_dev_aue.default.orders`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# COMMAND ----------\n",
    "from pyspark.sql.types import StructType, StructField, StringType, DoubleType\n",
    "\n",
    "# Clean landing zone for demo\n",
    "dbutils.fs.rm(\"/tmp/orders_raw/\", True)\n",
    "dbutils.fs.rm(\"/tmp/orders_checkpoint/\", True)\n",
    "\n",
    "# RE-CREATE THE DIRECTORY SO SPARK CAN ATTACH THE READSTREAM\n",
    "dbutils.fs.mkdirs(\"/tmp/orders_raw/\")\n",
    "\n",
    "csv_schema = StructType([\n",
    "    StructField(\"order_id\", StringType(), True),\n",
    "    StructField(\"customer_name\", StringType(), True),\n",
    "    StructField(\"email\", StringType(), True),\n",
    "    StructField(\"phone\", StringType(), True),\n",
    "    StructField(\"order_date\", StringType(), True),\n",
    "    StructField(\"status\", StringType(), True),\n",
    "    StructField(\"total_amount\", DoubleType(), True),\n",
    "    StructField(\"shipping_address\", StringType(), True),\n",
    "    StructField(\"city\", StringType(), True),\n",
    "    StructField(\"zip_code\", StringType(), True),\n",
    "    StructField(\"country\", StringType(), True),\n",
    "    StructField(\"carrier\", StringType(), True),\n",
    "    StructField(\"tracking_number\", StringType(), True),\n",
    "    StructField(\"estimated_delivery\", StringType(), True),\n",
    "    StructField(\"items\", StringType(), True),\n",
    "    StructField(\"support_notes\", StringType(), True)\n",
    "])\n",
    "\n",
    "# 1. Read Stream from the raw CSV landing directory (WITH RECURSIVE LOOKUP ENABLED!)\n",
    "stream_reader = (\n",
    "    spark.readStream\n",
    "    .format(\"csv\")\n",
    "    .option(\"header\", \"true\")\n",
    "    .option(\"recursiveFileLookup\", \"true\")\n",
    "    .schema(csv_schema)\n",
    "    .load(\"/tmp/orders_raw/\")\n",
    ")\n",
    "\n",
    "# 2. Write Stream incrementally to our catalog Delta Table\n",
    "stream_query = (\n",
    "    stream_reader.writeStream\n",
    "    .format(\"delta\")\n",
    "    .outputMode(\"append\")\n",
    "    .option(\"checkpointLocation\", \"/tmp/orders_checkpoint/\")\n",
    "    .table(\"adb_core_data_dev_aue.default.orders\")\n",
    ")\n",
    "\n",
    "print(\"Structured Streaming Query started and listening for new CSV drop files!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Step 3: Stream Batch Generator Function\n",
    "We define a function that generates a batch of synthetic orders and outputs them as a CSV into the landing directory. This will simulate a live feed."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# COMMAND ----------\n",
    "def generate_and_drop_streaming_csv(batch_name: str, count: int):\n",
    "    \"\"\"Generates mock orders and saves them as a CSV file in /tmp/orders_raw/\"\"\"\n",
    "    import pandas as pd\n",
    "    batch_orders = []\n",
    "    now_time = datetime.now()\n",
    "    \n",
    "    for i in range(count):\n",
    "        order_id = f\"STR-{batch_name}-{1000 + i}\"\n",
    "        customer_name = fake.name()\n",
    "        email = f\"{customer_name.lower().replace(' ', '.')}@{fake.free_email_domain()}\"\n",
    "        phone = fake.phone_number()\n",
    "        \n",
    "        # Ingest date\n",
    "        order_time = now_time - timedelta(minutes=random.randint(1, 1440))\n",
    "        status = random.choice([\"Processing\", \"Shipped\", \"Delivered\"])\n",
    "        total_amount = round(random.uniform(15.99, 450.00), 2)\n",
    "        items_list = [{\"category\": \"Electronics\", \"name\": \"Stream Ingestion Item\", \"price\": total_amount, \"quantity\": 1}]\n",
    "        \n",
    "        batch_orders.append({\n",
    "            \"order_id\": order_id,\n",
    "            \"customer_name\": customer_name,\n",
    "            \"email\": email,\n",
    "            \"phone\": phone,\n",
    "            \"order_date\": order_time.strftime(\"%Y-%m-%d %H:%M:%S\"),\n",
    "            \"status\": status,\n",
    "            \"total_amount\": total_amount,\n",
    "            \"shipping_address\": fake.street_address(),\n",
    "            \"city\": fake.city(),\n",
    "            \"zip_code\": fake.zipcode(),\n",
    "            \"country\": \"United States\",\n",
    "            \"carrier\": \"UPS\",\n",
    "            \"tracking_number\": f\"1Z{random.randint(1000000, 9999999)}\",\n",
    "            \"estimated_delivery\": (order_time + timedelta(days=3)).strftime(\"%Y-%m-%d\"),\n",
    "            \"items\": json.dumps(items_list),\n",
    "            \"support_notes\": f\"[{order_time.strftime('%Y-%m-%d %H:%M:%S')}] Ingested via Structured Streaming batch: {batch_name}\"\n",
    "        })\n",
    "        \n",
    "    # Save as CSV directly to the Autoload / Stream folder\n",
    "    pdf_batch = pd.DataFrame(batch_orders)\n",
    "    spark_df = spark.createDataFrame(pdf_batch)\n",
    "    \n",
    "    # Write as single coalesced CSV to avoid multi-part streaming conflicts\n",
    "    (\n",
    "        spark_df.coalesce(1)\n",
    "        .write.format(\"csv\")\n",
    "        .option(\"header\", \"true\")\n",
    "        .mode(\"overwrite\")\n",
    "        .save(f\"/tmp/orders_raw/{batch_name}\")\n",
    "    )\n",
    "        \n",
    "    print(f\"Successfully wrote streaming CSV Batch '{batch_name}' with {count} orders to '/tmp/orders_raw/'\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Step 4: Run Structured Ingestion (5000 + 5000 Orders)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# COMMAND ----------\n",
    "import time\n",
    "\n",
    "# 1. Trigger Batch A: Add 5,000 orders\n",
    "generate_and_drop_streaming_csv(\"batch_A\", 5000)\n",
    "time.sleep(12)  # Give Spark a few seconds to detect the file and process it\n",
    "\n",
    "count_a = spark.sql(\"SELECT COUNT(*) FROM adb_core_data_dev_aue.default.orders\").collect()[0][0]\n",
    "print(f\"Current Table Count after Batch A: {count_a} orders (Seed: 500 + Batch A: 5000)\")\n",
    "\n",
    "# 2. Trigger Batch B: Add another 5,000 orders\n",
    "generate_and_drop_streaming_csv(\"batch_B\", 5000)\n",
    "time.sleep(12)\n",
    "\n",
    "count_b = spark.sql(\"SELECT COUNT(*) FROM adb_core_data_dev_aue.default.orders\").collect()[0][0]\n",
    "print(f\"Current Table Count after Batch B: {count_b} orders (Seed: 500 + Batch A: 5000 + Batch B: 5000)\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Step 5: Define Spark SQL Execution Helper"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# COMMAND ----------\n",
    "import re\n",
    "\n",
    "def execute_spark_sql(sql: str):\n",
    "    \"\"\"Run read-only select commands directly on the Databricks cluster.\"\"\"\n",
    "    clean_sql = sql.strip().lower()\n",
    "    if not clean_sql.startswith(\"select\"):\n",
    "        return {\"error\": \"Only SELECT queries are allowed.\"}\n",
    "    \n",
    "    forbidden = [\"insert\", \"update\", \"delete\", \"drop\", \"alter\", \"create\", \"replace\", \"truncate\"]\n",
    "    for word in forbidden:\n",
    "        if re.search(r'\\b' + word + r'\\b', clean_sql):\n",
    "            return {\"error\": f\"Modifying query keyword '{word}' is not allowed.\"}\n",
    "            \n",
    "    try:\n",
    "        # Execute natively on Spark!\n",
    "        if \"from orders\" in clean_sql:\n",
    "            sql = re.sub(r'\\bfrom orders\\b', 'from adb_core_data_dev_aue.default.orders', sql, flags=re.IGNORECASE)\n",
    "        res_df = spark.sql(sql)\n",
    "        return [row.asDict() for row in res_df.limit(30).collect()]\n",
    "    except Exception as e:\n",
    "        return {\"error\": str(e)}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Step 6: Implement Agent Tools"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# COMMAND ----------\n",
    "def get_order_details(order_id: str) -> str:\n",
    "    \"\"\"Retrieve details of an order by ID (e.g. ORD-1025).\"\"\"\n",
    "    order_id = order_id.upper().strip()\n",
    "    if not order_id.startswith(\"ORD-\") and not order_id.startswith(\"STR-\"):\n",
    "        order_id = f\"ORD-{order_id}\"\n",
    "    \n",
    "    rows = execute_spark_sql(f\"SELECT * FROM adb_core_data_dev_aue.default.orders WHERE order_id = '{order_id}'\")\n",
    "    if isinstance(rows, dict) and \"error\" in rows:\n",
    "        return f\"Error: {rows['error']}\"\n",
    "    if not rows:\n",
    "        return f\"Order {order_id} not found.\"\n",
    "    return json.dumps(rows[0], indent=2)\n",
    "\n",
    "def search_orders(query_str: str) -> str:\n",
    "    \"\"\"Search for orders matching customer name or email.\"\"\"\n",
    "    sql = f\"\"\"\n",
    "    SELECT order_id, customer_name, email, order_date, status, total_amount, city \n",
    "    FROM adb_core_data_dev_aue.default.orders \n",
    "    WHERE customer_name LIKE '%{query_str}%' \n",
    "       OR email LIKE '%{query_str}%'\n",
    "    ORDER BY order_date DESC LIMIT 10\n",
    "    \"\"\"\n",
    "    rows = execute_spark_sql(sql)\n",
    "    if isinstance(rows, dict) and \"error\" in rows:\n",
    "        return f\"Error: {rows['error']}\"\n",
    "    if not rows:\n",
    "        return f\"No matching orders found.\"\n",
    "    return json.dumps(rows, indent=2)\n",
    "\n",
    "def get_analytics_summary() -> str:\n",
    "    \"\"\"Fetch aggregate order totals and counts by status.\"\"\"\n",
    "    count_sql = \"SELECT COUNT(*) as total_orders, ROUND(SUM(total_amount), 2) as total_revenue FROM adb_core_data_dev_aue.default.orders\"\n",
    "    status_sql = \"SELECT status, COUNT(*) as count, ROUND(SUM(total_amount), 2) as sales FROM adb_core_data_dev_aue.default.orders GROUP BY status\"\n",
    "    \n",
    "    stats = execute_spark_sql(count_sql)\n",
    "    status_breakdown = execute_spark_sql(status_sql)\n",
    "    \n",
    "    summary = {\n",
    "        \"overall\": stats[0] if stats else {},\n",
    "        \"status_distribution\": status_breakdown\n",
    "    }\n",
    "    return json.dumps(summary, indent=2)\n",
    "\n",
    "def run_read_only_sql_query(sql: str) -> str:\n",
    "    \"\"\"Run custom SELECT query directly on Delta Table.\"\"\"\n",
    "    res = execute_spark_sql(sql)\n",
    "    if isinstance(res, dict) and \"error\" in res:\n",
    "        return f\"SQL Error: {res['error']}\"\n",
    "    return json.dumps(res, indent=2)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Step 7: Implement Multi-Agent Routing Engine"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# COMMAND ----------\n",
    "import time\n",
    "import json\n",
    "import re\n",
    "\n",
    "def run_agent_fallback(user_query: str):\n",
    "    \"\"\"Local rule/NLP fallback if no Gemini key is provided.\"\"\"\n",
    "    print(\"[Routing Agent] Analyzing query intent...\")\n",
    "    time.sleep(0.3)\n",
    "    q_lower = user_query.lower()\n",
    "\n",
    "    order_id_match = re.search(r'\\b(ord-|str-)?\\d{4,5}\\b', q_lower)\n",
    "    if order_id_match:\n",
    "        raw_id = order_id_match.group()\n",
    "        norm_id = raw_id.upper()\n",
    "        print(f\"[Router] Routing to Order Retrieval Agent for Order: {norm_id}\")\n",
    "        details_str = get_order_details(norm_id)\n",
    "        if \"not found\" in details_str:\n",
    "            return f\"I couldn't find a record for order ID **{norm_id}** in our Databricks Delta table.\"\n",
    "        \n",
    "        o = json.loads(details_str)\n",
    "        return f\"### Order Details for **{o['order_id']}**\\n- **Customer**: {o['customer_name']}\\n- **Status**: `{o['status']}`\\n- **Total**: ${o['total_amount']:.2f}\\n- **Carrier**: {o['carrier']}\\n- **Tracking**: `{o['tracking_number']}`\\n- **Notes Log**:\\n```\\n{o['support_notes']}\\n```\"\n",
    "        \n",
    "    analytics_keywords = [\"how many\", \"revenue\", \"sales\", \"average\", \"stats\", \"analytics\", \"breakdown\"]\n",
    "    if any(kw in q_lower for kw in analytics_keywords):\n",
    "        print(\"[Router] Routing to Analytics Agent...\")\n",
    "        stats = json.loads(get_analytics_summary())\n",
    "        total_rev = stats[\"overall\"].get(\"total_revenue\", 0.0)\n",
    "        total_ord = stats[\"overall\"].get(\"total_orders\", 0)\n",
    "        \n",
    "        resp = f\"### Databricks Delta Lake Summary\\n- **Total Revenue**: ${total_rev:,.2f}\\n- **Total Active Volume**: {total_ord:,} orders\\n\\n**Breakdown**:\\n\"\n",
    "        for row in stats[\"status_distribution\"]:\n",
    "            resp += f\"- **{row['status']}**: {row['count']} orders (${row['sales']:,.2f} sales)\\n\"\n",
    "        return resp\n",
    "        \n",
    "    print(\"[Router] Routing to Order Retrieval Agent (Search)...\")\n",
    "    search_res = search_orders(user_query)\n",
    "    if \"No matching\" in search_res:\n",
    "        return \"I am your Databricks Multi-Agent RAG. Try asking:\\n- *What is the status of order ORD-1025?*\\n- *How many orders are processing?*\\n- *Search for customer John*\"\n",
    "        \n",
    "    results = json.loads(search_res)\n",
    "    resp = \"### Search Matches in Databricks Table:\\n\\n| Order ID | Customer | Status | Total | City |\\n|---|---|---|---|---|\\n\"\n",
    "    for r in results:\n",
    "         resp += f\"| **{r['order_id']}** | {r['customer_name']} | `{r['status']}` | ${r['total_amount']:.2f} | {r['city']} |\\n\"\n",
    "    return resp\n",
    "\n",
    "def run_agent_gemini(user_query: str, api_key: str):\n",
    "    \"\"\"Gemini Orchestrator executing live tool calls over the Delta table.\"\"\"\n",
    "    from google import genai\n",
    "    from google.genai import types\n",
    "    \n",
    "    client = genai.Client(api_key=api_key)\n",
    "    tool_map = {\n",
    "        \"get_order_details\": get_order_details,\n",
    "        \"search_orders\": search_orders,\n",
    "        \"get_analytics_summary\": get_analytics_summary,\n",
    "        \"run_read_only_sql_query\": run_read_only_sql_query\n",
    "    }\n",
    "    \n",
    "    prompt = f\"\"\"You are a Multi-Agent RAG Orchestrator managing a Databricks Delta table. \n",
    "Table: `adb_core_data_dev_aue.default.orders`\n",
    "Process user query: \"{user_query}\"\n",
    "\"\"\"\n",
    "    chat_contents = [prompt]\n",
    "    for _ in range(5):\n",
    "        response = client.models.generate_content(\n",
    "            model='gemini-2.5-flash',\n",
    "            contents=chat_contents,\n",
    "            config=types.GenerateContentConfig(\n",
    "                tools=[get_order_details, search_orders, get_analytics_summary, run_read_only_sql_query],\n",
    "                temperature=0.0\n",
    "            )\n",
    "        )\n",
    "        \n",
    "        if not response.function_calls:\n",
    "            return response.text\n",
    "            \n",
    "        for call in response.function_calls:\n",
    "            print(f\"[Gemini Orchestrator] Executing tool '{call.name}' with args: {json.dumps(call.args)}\")\n",
    "            tool_func = tool_map.get(call.name)\n",
    "            result = tool_func(**call.args) if tool_func else \"Error: Tool not found.\"\n",
    "            \n",
    "            chat_contents.append(response)\n",
    "            func_resp_part = types.Part.from_function_response(name=call.name, response={\"result\": result})\n",
    "            chat_contents.append(types.Content(role=\"user\", parts=[func_resp_part]))\n",
    "            \n",
    "    return \"Agent failed to return response under loop limit.\"\n",
    "\n",
    "def query_databricks_rag(user_query: str, api_key: str = None):\n",
    "    if api_key:\n",
    "        try:\n",
    "            return run_agent_gemini(user_query, api_key)\n",
    "        except Exception as e:\n",
    "            print(f\"Gemini failed: {str(e)}. Running Local Fallback...\")\n",
    "            return run_agent_fallback(user_query)\n",
    "    else:\n",
    "        return run_agent_fallback(user_query)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbformat": "mime",
   "nbformat_minor": 2,
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

with open("databricks_notebook.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)
print("databricks_notebook.ipynb created successfully in workspace!")
